on:

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run AddUsersTest
    steps:
    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v2
    - uses: actions/checkout@v1
    - name: Run tests
      run: mvn clean test
